"""The contiguous United States, drawn at the resolution of land prices.

The world map in this directory has to model urban land value from GDP, because
no global measurement of it exists.  The United States is the one large country
where that compromise is unnecessary.  Nolte (2020) trained tree ensembles on
six million arm's-length land sales and published fair-market-value estimates
for every 480 m cell of the conterminous US -- close to parcel scale, and the
only dataset of its kind at national extent.

This script pours that surface into a density-equalising cartogram.  Tiles are
uniform ground and what varies is what the ground is worth, so the tile that
swells is the expensive one.  There are three cuts:

    make_us_cartogram.py us     3.84 km tiles, the whole conterminous US
    make_us_cartogram.py nyc    480 m tiles, 220 km around New York
    make_us_cartogram.py bay    480 m tiles, 220 km around San Francisco

The metro cuts run the source at its native resolution: a 480 m tile in
Manhattan is about two city blocks, which is as close to a parcel as any
national dataset gets.

Two things to hold onto while reading the map:

  * The values are *predicted* market prices, not transactions.  Nolte reports
    out-of-sample accuracy in the paper; error is largest exactly where sales
    are thin, which is the empty interior.
  * The estimates are for land alone (the `vacant` model), so a city block is
    priced as the dirt under the building, not the building.

Writes docs/figures/land_value_cartogram_<cut>.html and
data/land/us_cartogram_check_<cut>.csv.
"""

import base64
import hashlib
import json
import sys
import zlib
from pathlib import Path

import geopandas as gpd
import numpy as np
import pandas as pd
import rasterio
import shapely.geometry
import shapely.ops
from rasterio.features import rasterize
from rasterio.transform import from_bounds
from shapely.geometry import Polygon

sys.path.insert(0, str(Path(__file__).resolve().parent))
from cartogram import DiffusionCartogram  # noqa: E402
from make_cartogram import _esc, densify  # noqa: E402

ROOT = Path(__file__).resolve().parents[2]
IN = ROOT / "data" / "land" / "inputs"
DATA = ROOT / "data" / "land"
FIG = ROOT / "docs" / "figures"
CACHE = DATA / "cache"

# The "vacant" model prices the dirt; the "all" model prices dirt plus
# whatever is standing on it.  Land, in the sense the national accounts mean
# by AN.211, is the first one.
FMV = IN / "places_fmv" / "places_fmv_vacant.tif"

ALBERS = "EPSG:5070"     # equal-area, so the input areas mean something
# Below this private share a tile is not drawn at all: see _land_tiles.
MIN_PRIVATE = 0.25
STEPS = 170
# The drawing box and the deepest zoom the page allows.  Both are quoted in the
# JS below, and the outline tolerance is derived from them, so they live here
# rather than being written out three times and drifting apart.
DRAW_W = 2000.0
MAX_ZOOM = 400.0
# Smallest metro area that gets a name on the map: see _metros().  A round
# million left out Charleston, South Carolina at 817,756 -- and with it
# Bridgeport, Bakersfield, McAllen, Worcester and Oxnard, which sit in the same
# gap.  There is nothing measured about either number; 800,000 is where the
# line is drawn now, and the six it admits are named below so the choice is
# legible rather than buried.
MIN_METRO = 800_000

# The 480 m CONUS Albers lattice both surfaces are cut from.  It is the
# PLACES raster's own grid; the GDP surface is binned onto the same one so the
# two maps are the same tiles and can be divided by each other.
GRID = dict(x0=-2357205.0, y1=3173925.0, res=480.0, nx=9618, ny=6054)

_LAND_NOTE = """<b>Limits.</b> The values are model predictions, not sales, and
are least reliable where sales are thinnest. They price land only, not the
buildings on it. Every acre is included, including ground with no market: the
model puts $1.04m per km&sup2; on the interior of Yellowstone, and that is in
this total."""

_GDP_NOTE = """<b>Limits.</b> GDP is measured by county and nothing finer, so
within a county this map knows only where the jobs, the people and the fields
are: two blocks with the same headcount get the same output. Mining and oil are
placed by workplace, so an oilfield county piles its output onto the few
squares that hold an office."""

# The single number this map is made of, said plainly, with worked cases from
# the shipped tiles.  Every figure below is read off data/land/us_land_vs_gdp.csv.gz
# and is regenerated by src/land/ratio_examples.py, so the prose cannot drift
# away from the map.
_RATIO_HOWTO = """<b>What the number is.</b> Take one 3.84&nbsp;km square. It
holds some amount of land, worth some number of dollars, and some amount of
activity, which produces some number of dollars of output every year. Divide
the first by the second. Dollars over dollars-a-year leaves <b>years</b>: how
long the work done on that ground would have to run to equal the price of the
ground itself. It is a price-to-earnings ratio, with the land as the asset and
the local economy as the earnings.<br><br>
Nationally the answer is <b>0.34 years</b> &mdash; all the privately held land
in the lower 48 is worth about four months of what is produced on it. That is
the midpoint of the colour scale. Everything else is measured against it.<br><br>
<b>Low (teal) is working ground.</b> The Cleveland Flats run at
<b>0.08 years</b>: $210m of land carrying $2.5bn of output a year. Midtown
Manhattan &mdash; the most expensive dirt in the country at $17.7bn a square
&mdash; is also teal, at <b>0.04 years</b>, because the $419bn produced on it
each year dwarfs even that price. Dear and cheap are not the same axis as brown
and teal.<br><br>
<b>High (brown) is ground priced for something other than the work on it.</b>
Cape Cod runs at <b>4.0 years</b>, a hundred times Manhattan: the land is
expensive because people want to be there, not because anyone works there. Napa
sits at <b>1.3 years</b>, vineyard ground priced on decades of future vintages
rather than on this year's payroll. Silicon Valley in Mountain View is
<b>0.83 years</b> &mdash; genuinely productive, but its land price has run ahead
even of that.<br><br>
<b>Where the output is put.</b> County GDP is measured; everything finer is
allocation, and this map allocates each part of it to the thing that produces
it. The output of dwellings &mdash; rent paid, plus the rent the BEA imputes to
owner-occupiers &mdash; goes on the housing, 13.4% of national GDP. Agriculture
goes on the farmed hectares, from the USDA crop map. The other 85.7% goes on
the jobs, counted where people work &mdash; and each industry on the jobs of
that industry, so a refinery block and a school block in the same county are no
longer given the same output. So a subdivision is <i>not</i> brown by
construction: it is brown because what a house earns in a year is small beside
its price. Grey is ground with no workplace on it, where the output is known
only by the county and the map declines to claim a resolution its denominator
does not have; how much of the page that is, is printed on every build and
given in the write-up.<br><br>
<b>What is still misplaced.</b> Mines, power plants and 104,753 producing wells
now carry their own output &mdash; Loving County, Texas has $10.7bn of output
and not one census block with a mining job on it, so its oil used to be drawn
on its gas stations. What is left is 2.5% of the mining line, in counties with
no site of any kind: company headquarters, where the office may be the right
answer anyway, and the Louisiana and Texas coast, where the production is
offshore and the county it is booked to is only where the boats leave from.<br><br>
<b>What the blank areas are.</b> The national parks and the military
installations &mdash; 1.4% of the lower 48 &mdash; are taken out of the
numerator here, because the land model prices them as though they were for sale
and they are not: $1.04m per km&sup2; for the interior of Yellowstone. A tile
less than a quarter of which is in the market is not drawn at all. The
land-value map does <i>not</i> do this: it shows every acre, because a total
of American land value that quietly omits the parks would be the wrong
number.<br><br>
<b>One place to distrust.</b> Indiana's cities and industrial districts carry
almost no urban premium in the land model &mdash; Gary's mill ground prices
eight times below the median of comparable districts in other states, Fort
Wayne fifteen times below its peer metros &mdash; while rural Indiana prices
exactly like rural Ohio. Indiana therefore reads far more teal here than it
should. That is the land surface, not Indiana's economy.<br><br>
<b>What it is not.</b> Not GDP per person. Not a rate of return, and not a
verdict on whether anything is over- or under-priced."""

_RATIO_NOTE = """<b>What this cannot tell you.</b> The two surfaces are
different vintages and different rules: land is Nolte&rsquo;s 2020-dollar
model of what private land would sell for, output is BEA county GDP for 2023
placed by where the work, the housing and the farming are. A stock
over a flow gives units of years, and the land model compresses the top of the
price distribution, so the ratio understates how dear the most expensive ground
really is. This is a comparison of two maps, not a measured statistic."""

_TAIL = """ The source stops at the conterminous states, so Alaska and Hawaii
are absent, and a cartogram equalises density only approximately: this one is
drawn to within 6.9% of each tile&rsquo;s share of the total, checked on every
build."""

# Named cuts.  The national maps trade resolution for extent; the metro cuts
# run at 480 m, which is where "parcel level" stops being a figure of speech --
# a 480 m tile in Manhattan is about two city blocks.
def _cut(block, nx, title, where, window, src="land", mesh=None,
         diverge=False, flat=False, title_note=None):
    land = src == "land"
    return dict(
        block=block, nx=nx, title=title, where=where, window=window, src=src,
        mesh=mesh, diverge=diverge, flat=flat,
        # Relaxation helps the land field and hurts the output field.  Land
        # prices vary smoothly; output does not -- it stands in point masses at
        # the blocks where the jobs are, and feeding a map full of collapsed
        # tiles back in as a density makes the next pass worse, not better.
        passes=3 if land else 1,
        quantity=("land value, coloured by what it earns" if diverge
                  else "land value" if land else "GDP"),
        noun="of land" if land else "of GDP",
        colour=(("Every tile is the same patch of ground drawn where it "
                 "belongs, so nothing here is distorted and area carries no "
                 "meaning &mdash; only the colour does. It is one tile&rsquo;s "
                 "land value divided by the annual output produced on that "
                 "same tile, set against the national figure. "
                 if flat else
                 "Area is still land value, exactly as on the price map; only "
                 "the colour has changed. It is one tile&rsquo;s land value "
                 "divided by the annual output produced on that same tile, "
                 "set against the national figure. ") +
                "<b>Brown</b> ground costs more than the work done on it can "
                "account for. <b>Teal</b> ground carries more work than its "
                "price implies. <b>Grey</b> is land with no workplace on it, "
                "where the output is known only by county and is not drawn "
                "at this scale."
                if diverge else
                "The shade is land value per square kilometre of real ground."
                if land else
                "The shade is GDP per square kilometre of real ground."),
        caption=("land value per km&sup2; of real ground" if land
                 else "GDP per km&sup2; of real ground"),
        notes=((_RATIO_HOWTO + "<br><br>" + _RATIO_NOTE) if diverge
               else _LAND_NOTE if land else _GDP_NOTE) + _TAIL,
    )


REGIONS = {
    "us": _cut(8, 4608, "What American land is worth",
               "the contiguous United States", None),
    "nyc": _cut(1, 3072, "What land is worth around New York",
                "a 220 km square around New York", (-74.0, 40.75, 220)),
    "bay": _cut(1, 3072, "What land is worth around San Francisco",
                "a 220 km square around San Francisco", (-122.3, 37.8, 220)),
    "usgdp": _cut(8, 4608, "American output, drawn where it is produced",
                  "the contiguous United States", None, "gdp"),
    # Same geometry as `us` -- area is still land value -- but coloured by how
    # far the ground departs from the national ratio of land value to output.
    # It reuses that cut's transported mesh, so it costs a render, not a solve.
    "usratio": _cut(8, 4608, "Dear ground, cheap ground",
                    "the contiguous United States", None, mesh="us",
                    diverge=True),
    # The same comparison undeformed.  A ratio is an attribute of a place, not
    # a quantity to be summed, so there is nothing for a cartogram to encode in
    # area -- equal ground is the honest frame for it.
    "usratioflat": _cut(8, 4608, "Dear ground, cheap ground",
                        "the contiguous United States", None,
                        diverge=True, flat=True),
}

# Stops of a continuous scale in log price per km2; the ends are set per cut
# from the tiles themselves, because a metro spans a hundredfold and the
# country spans a millionfold.
RAMP = ["#cde2fb", "#9ec5f4", "#6da7ec", "#3987e5",
        "#256abf", "#184f95", "#0d366b"]

# Diverging, for the one map that has a sign.  Brown-to-teal is colour-blind
# safe and the midpoint is a true neutral rather than a near-white, so it holds
# up on a dark ground as well as a light one.
DIVERGE = ["#01665e", "#35978f", "#80cdc1", "#9a9a9a",
           "#dfc27d", "#bf812d", "#8c510a"]
NOVAL = "#7d838c"      # land whose output is known only by county

_SRC_LAND = ('Land value: Nolte, <a href="https://doi.org/10.1073/pnas.2012'
             '865117">&ldquo;High-resolution land value maps&hellip;&rdquo;'
             '</a>, <i>PNAS</i> 117:47 (2020) &mdash; the PLACES vacant-land '
             'model, 480 m, fitted to six million arm&rsquo;s-length sales '
             '(<a href="https://doi.org/10.5281/zenodo.4073355">Zenodo</a>, '
             'CC-0).')
_SRC_GDP = ("Output: BEA county GDP for 2023 (CAGDP2) on twenty industry "
            "lines, placed inside each county by what produces it &mdash; "
            "85.7% on Census LEHD LODES8 workplace counts, <i>each line on "
            "the jobs of its own industry</i>; 13.4% on tract housing "
            "services from the ACS; 0.8% on USDA Cropland Data Layer "
            "hectares, priced against the 2022 Census of Agriculture. Mines "
            "(MSHA), power plants (EIA-860) and producing wells "
            "(FracFocus, and CalGEM for California) carry their own sectors "
            "from their own coordinates.")
# Written from the constant, not typed: this line said "over a million" for a
# while after the floor moved to 800,000, which is the map describing itself
# wrongly.
_SRC_NAMES = (f"Cities: Census metropolitan areas over {MIN_METRO:,.0f} "
              "people (ACS 2023), at their largest place.")

PROVENANCE = {
    "land": _SRC_LAND + " " + _SRC_NAMES,
    "ratio": (_SRC_LAND + " " + _SRC_GDP + " Parks and military land are "
              "excluded here. " + _SRC_NAMES),
    "gdp": _SRC_GDP + " " + _SRC_NAMES,
}


def main(argv):
    key = argv[1] if len(argv) > 1 else "us"
    if key not in REGIONS:
        raise SystemExit(f"usage: make_us_cartogram.py [{'|'.join(REGIONS)}]")
    r = REGIONS[key]

    value, geo, real = tile_values(r["block"], r["window"], r["src"],
                                   private=r["diverge"])
    lattice, tiles, quads = build_mesh(value)
    extent, field = ((None, None) if r["flat"]
                     else solver_field(value, geo, r["nx"]))

    # The flow grid cell: the finest scale the deformation can carry.
    borders, postal = state_borders(
        geo, flat=r["flat"], cell=geo["tx"] * geo["side"] / r["nx"])
    # Kept fixed: the anchors ride the flow, so changing the count invalidates
    # every cached mesh.  Which of them get drawn is decided in the browser.
    city_name, city_xy = cities(geo, 420)
    mshapes = metro_bounds(geo, MIN_METRO if geo["window"] is None else 0.0,
                           r["flat"], geo["tx"] * geo["side"] / r["nx"])
    pts, bidx, midx, lab0 = pack_points(lattice, geo, borders, city_xy,
                                        metros=mshapes)
    if r["flat"]:
        print(f"\n{len(pts):,d} vertices, undeformed "
              f"({len(lattice):,d} lattice + {len(pts)-len(lattice):,d} "
              "on borders)")
    else:
        print(f"\nDiffusion grid {r['nx']}x{field.shape[0]}, {len(pts):,d} "
              f"vertices ({len(lattice):,d} lattice + "
              f"{len(pts)-len(lattice):,d} on borders)")

    # A flat map needs no flow: the tiles stay where the ground is.
    moved = (pts if r["flat"]
             else cached(key, r, field, extent, pts, quads,
                         value.ravel()[tiles]))

    render(key, r, value, geo, tiles, quads, moved, len(lattice),
           bidx, postal, city_name, lab0, real.ravel()[tiles], midx=midx)
    return 0


# --- the value surface ----------------------------------------------------

def tile_values(block, window, src="land", private=False):
    """Tile totals on the 480 m CONUS lattice, from whichever surface.

    Returns the value grid, the geometry, and a mask of the tiles that are
    real.  They differ only for GDP: no workplace stands on most American
    ground, so most land tiles produce nothing, and a tile of nothing cannot be
    drawn with no area at all.  Those tiles are kept in the mesh at a floor
    value so the sheet does not tear and so empty land shrinks instead of
    drifting at the average -- but they are not drawn, and the accuracy check
    reports how much of the page the floor absorbs.
    """
    geo = _geo(block, window)
    if src == "land":
        out = _land_tiles(geo, block, window, private)
        real = out > 0
    else:
        out = _gdp_tiles(geo)
        real = out > 0
        land = _land_tiles(geo, block, window) > 0
        area = (geo["side"] / 1000.0) ** 2
        floor = np.percentile(out[real] / area, 1) * area
        fill = land & ~real
        out = np.where(fill, floor, out)
        print(f"  {int(real.sum()):,d} tiles produce something; "
              f"{int(fill.sum()):,d} land tiles produce nothing recorded and "
              f"are held at a floor of ${floor/area:,.0f}/km2, "
              f"{floor*fill.sum()/out.sum():.2%} of the page")
    n = int((out > 0).sum())
    side = geo["side"]
    what = "land" if src == "land" else "output"
    print(f"{n:,d} tiles of {side/1000:.2f} x {side/1000:.2f} km "
          f"covering ${out.sum()/1e12:,.3f}tn of {what}")
    print(f"  ground {n * (side/1000)**2:,.0f} km2; "
          f"tile value ${out[out>0].min()/1e6:,.3f}m to "
          f"${out.max()/1e9:,.2f}bn, a factor of "
          f"{out.max()/out[out>0].min():,.0f}")
    return out, geo, real


def _geo(block, window):
    """Where this cut sits on the shared lattice."""
    col0, row0, ncol, nrow = _window(window)
    return dict(x0=GRID["x0"] + col0 * GRID["res"],
                y1=GRID["y1"] - row0 * GRID["res"],
                side=GRID["res"] * block,
                tx=ncol // block, ty=nrow // block,
                col0=col0, row0=row0, window=window)


def _gdp_tiles(geo, kinds=(0, 1, 2)):
    """Sum the point-level GDP allocation into tiles.

    Two kinds of point arrive: census blocks carrying the output of their jobs,
    and population cells carrying the output of the housing on them.  Each is a
    single coordinate, so it lands wholly in one tile.  At 480 m that is a real
    approximation -- a rural census block can be larger than a tile and a
    population cell is about 800 m across -- but in cities, where the money is,
    both are far smaller than the tile.
    """
    z = np.load(DATA / "us_gdp_points.npz")
    ix = np.floor((z["x"] - geo["x0"]) / geo["side"]).astype(np.int64)
    iy = np.floor((geo["y1"] - z["y"]) / geo["side"]).astype(np.int64)
    keep = ((ix >= 0) & (ix < geo["tx"]) & (iy >= 0) & (iy < geo["ty"])
            & np.isin(z["kind"], kinds))
    out = np.zeros(geo["ty"] * geo["tx"], dtype=np.float64)
    np.add.at(out, iy[keep] * geo["tx"] + ix[keep], z["gdp"][keep].astype(float))
    if len(kinds) == 3:
        kind = z["kind"][keep]
        n = [int((kind == k).sum()) for k in (0, 1, 2)]
        print(f"{int(keep.sum()):,d} of {len(ix):,d} points fall inside this "
              f"cut ({n[0]:,d} job blocks, {n[1]:,d} population cells, "
              f"{n[2]:,d} farmland cells), carrying "
              f"${z['gdp'][keep].sum()/1e12:,.3f}tn")
    return out.reshape(geo["ty"], geo["tx"])


def _land_tiles(geo, block, window, private=False):
    """Block-sum the 480 m fair-market-value raster into tiles.

    The raster stores the natural log of value per hectare, so it has to be
    exponentiated before anything is added up -- summing logs would silently
    compute a geometric mean.  With block=1 no aggregation happens at all and
    the tiles are the source cells.
    """
    ha_per_cell = (480 / 100.0) ** 2       # 480 m square = 23.04 ha
    ty, tx, col0, row0 = geo["ty"], geo["tx"], geo["col0"], geo["row0"]
    priv = _private_share() if private else None

    with rasterio.open(FMV) as src:
        if (src.width, src.height) != (GRID["nx"], GRID["ny"]):
            raise SystemExit("the raster is not the lattice GRID describes")
        out = np.zeros((ty, tx), dtype=np.float64)
        step = max(640 // block, 1) * block          # ~640 source rows at a time
        for a in range(0, ty * block, step):
            b = min(a + step, ty * block)
            arr = src.read(1, window=rasterio.windows.Window(
                col0, row0 + a, tx * block, b - a)).astype(np.float64)
            v = np.where(np.isfinite(arr) & (arr > 0), np.exp(arr) * ha_per_cell, 0.0)
            if priv is not None:
                v *= priv[row0 + a:row0 + b, col0:col0 + tx * block]
            out[a // block:b // block] = v.reshape(
                (b - a) // block, block, tx, block).sum(axis=(1, 3))
    if priv is not None:
        # A tile that is nearly all national forest still holds the output of
        # whatever is done on the forest, against the price of the sliver that
        # is private.  The ratio there is a comparison of two different pieces
        # of ground, so the tile is dropped rather than drawn misleadingly
        # cheap.  It costs a fraction of a percent of the land value.
        sh = priv[row0:row0 + ty * block,
                  col0:col0 + tx * block].reshape(ty, block, tx,
                                                  block).mean(axis=(1, 3))
        drop = sh < MIN_PRIVATE
        if drop.any():
            print(f"  {int((drop & (out > 0)).sum()):,d} tiles are less than "
                  f"{MIN_PRIVATE:.0%} private and are not drawn "
                  f"({out[drop].sum()/out.sum():.2%} of the land value)")
            out[drop] = 0.0
    return out


def _private_share():
    """The share of each 480 m cell that is in private hands, or None.

    The land model predicts a market value for every cell in the country,
    including the ones no one could sell -- the interior of Yellowstone comes
    out at $1.04m per km2.  Multiplying by this before the tiles are summed
    makes the map's land value the value of land that could change hands.
    Built by src/land/build_us_public_land.py from PAD-US; if that has not been
    run the figures still build, on the raw surface, and say so.
    """
    f = DATA / "us_private_share.npy"
    if not f.exists():
        print("  (no data/land/us_private_share.npy: public land is priced "
              "as though it were for sale -- run build_us_public_land.py)")
        return None
    return np.load(f).astype(np.float32) / 255.0


def _window(window):
    """The whole lattice, or a square of `km` centred on a lon/lat."""
    if window is None:
        return 0, 0, GRID["nx"], GRID["ny"]
    import pyproj
    lon, lat, km = window
    x, y = pyproj.Transformer.from_crs(4326, ALBERS, always_xy=True).transform(
        lon, lat)
    half = km * 1000 / 2
    col0 = max(int((x - half - GRID["x0"]) / GRID["res"]), 0)
    row0 = max(int((GRID["y1"] - y - half) / GRID["res"]), 0)
    n = int(km * 1000 / GRID["res"])
    return (col0, row0, min(n, GRID["nx"] - col0), min(n, GRID["ny"] - row0))


def solver_field(value, geo, nx):
    """The density the flow will equalise, on a padded grid.

    Everything outside the estimated area -- ocean, Canada, Mexico -- is set to
    the mean density of the land.  That is the usual Gastner-Newman choice: a
    background at the mean neither swells nor shrinks, so it acts as a passive
    cushion rather than crushing the map against the frame.
    """
    pad = 0.15 * max(geo["tx"], geo["ty"]) * geo["side"]
    x0 = geo["x0"] - pad
    x1 = geo["x0"] + geo["tx"] * geo["side"] + pad
    y1 = geo["y1"] + pad
    y0 = geo["y1"] - geo["ty"] * geo["side"] - pad
    ny = max(int(round(nx * (y1 - y0) / (x1 - x0) / 64)), 1) * 64
    NX = nx
    dx, dy = (x1 - x0) / NX, (y1 - y0) / ny

    density = value / (geo["side"] ** 2 / 1e6)     # $ per km2
    cx = x0 + (np.arange(NX) + 0.5) * dx
    cy = y1 - (np.arange(ny) + 0.5) * dy
    ix = np.floor((cx - geo["x0"]) / geo["side"]).astype(np.int64)
    iy = np.floor((geo["y1"] - cy) / geo["side"]).astype(np.int64)
    inx = (ix >= 0) & (ix < geo["tx"])
    iny = (iy >= 0) & (iy < geo["ty"])
    field = np.zeros((ny, NX))
    field[np.ix_(iny, inx)] = density[np.ix_(iy[iny], ix[inx])]

    hit = field > 0
    field = np.where(hit, field, field[hit].mean())
    return (x0, x1, y0, y1), field


# --- mesh -----------------------------------------------------------------

def build_mesh(value):
    """One shared vertex per lattice corner, so the mesh cannot tear."""
    ty, tx = value.shape
    keep = value > 0
    corners = np.zeros((ty + 1, tx + 1), dtype=bool)
    for oy in (0, 1):
        for ox in (0, 1):
            corners[oy:oy + ty, ox:ox + tx] |= keep

    vid = np.full((ty + 1, tx + 1), -1, dtype=np.int64)
    vid[corners] = np.arange(int(corners.sum()))
    cy, cx = np.nonzero(corners)
    lattice = np.empty((len(cy), 2), dtype=np.int64)
    lattice[:, 0] = cx
    lattice[:, 1] = cy

    iy, ix = np.nonzero(keep)
    tiles = iy * tx + ix
    quads = np.stack([vid[iy, ix], vid[iy, ix + 1],
                      vid[iy + 1, ix + 1], vid[iy + 1, ix]], axis=1)
    return lattice, tiles, quads


def pack_points(lattice, geo, borders, anchors, metros=None):
    """Lattice corners, border rings and label anchors in one array.

    They all ride the same flow, so the state outlines and their names still
    sit where the tiles put them once the map has been pulled about.
    """
    xy = np.empty((len(lattice), 2))
    xy[:, 0] = geo["x0"] + lattice[:, 0] * geo["side"]
    xy[:, 1] = geo["y1"] - lattice[:, 1] * geo["side"]

    chunks = []
    n = len(xy)

    def rings(gs):
        nonlocal n
        out = []
        for i, geom in enumerate(gs):
            polys = [geom] if geom.geom_type == "Polygon" else list(geom.geoms)
            for p in polys:
                for r in [p.exterior] + list(p.interiors):
                    c = np.asarray(r.coords)
                    out.append((i, n, len(c)))
                    chunks.append(c)
                    n += len(c)
        return out

    idx = rings(borders.geometry)
    midx = rings(metros.geometry) if metros is not None else []
    lab0 = n
    chunks.append(np.asarray(anchors, dtype=float))
    return np.vstack([xy] + chunks), idx, midx, lab0


_METRO_CACHE = {}


def metro_bounds(geo, floor, flat, cell):
    """The outlines of the metro areas the map names, clipped to the cut.

    Same two tolerances as the state outlines, and for the same reasons: these
    rings ride the flow too, so on a cartogram they cannot carry detail finer
    than the flow grid.  They are drawn only when the reader asks for them.
    """
    m = _METRO_CACHE.get("shapes")
    if m is None:
        _metros(floor)
        m = _METRO_CACHE["shapes"]
    box = shapely.geometry.box(
        geo["x0"], geo["y1"] - geo["ty"] * geo["side"],
        geo["x0"] + geo["tx"] * geo["side"], geo["y1"])
    g = m.copy()
    g["geometry"] = g.geometry.intersection(box)
    g = g[~g.geometry.is_empty & (g.geometry.area > 0)].reset_index(drop=True)
    tol = max(geo["tx"] * geo["side"] / DRAW_W / MAX_ZOOM, 5.0)
    if not flat and cell:
        tol = max(tol, cell / 2.0)
    g["geometry"] = [q.simplify(tol).buffer(0) for q in g.geometry]
    if not flat:
        g["geometry"] = [densify(q, max(geo["side"], 2000.0))
                         for q in g.geometry]
    return g[~g.geometry.is_empty].reset_index(drop=True)


def _metros(floor):
    """The metropolitan areas over a million people, one name each.

    A metro area is a defined object, not a guess: the Census delineates 393
    Metropolitan Statistical Areas by commuting to an urban core, names each
    one after its principal cities, and the ACS counts them.  Fifty-six are
    over a million.  Taking the first name off the title -- Austin off
    "Austin-Round Rock-San Marcos, TX" -- gives the primary city, so the map
    names each metro once, at its centre, and never twice.

    That replaces ranking Natural Earth's places by POP_MAX, which cannot be
    made to do this.  POP_MAX is an agglomeration figure attached to whichever
    place the file happens to carry, so it ranked Irvine fifteenth in the
    country on the Anaheim-Santa Ana total, ahead of San Diego, and offered
    Oakland, Mesa, Long Beach, Fort Worth and St. Paul as separate cities from
    the metros they belong to.

    Natural Earth is still what puts the dot on the ground: the primary city is
    matched to its place by name inside the metro's own boundary, which works
    for 52 of the 56.  The other four fall back to the largest place inside the
    boundary, and all of them land where they should -- Washington, D.C. for
    Washington, Louisville for "Louisville/Jefferson County", Honolulu for
    "Urban Honolulu".  The label is then the place's own name, which is why the
    map says Louisville rather than Louisville/Jefferson County.
    """
    import re

    def norm(s):
        return re.sub(r"[^a-z]", "", s.lower().replace("saint", "st"))

    c = gpd.read_file(f"zip://{IN / 'cb_2023_us_cbsa_500k.zip'}").to_crs(ALBERS)
    d = pd.read_csv(IN / "acs" / "acsdt5y2023-b01003.dat", sep="|",
                    dtype={"GEO_ID": str}, low_memory=False)
    def level(prefix):
        s = d[d.GEO_ID.str.startswith(prefix)]
        return s.assign(G=s.GEO_ID.str[9:]).set_index("G")[
            "B01003_E001"].astype(float)

    pop, csa = level("310M700US"), level("330M700US")   # metro, then combined

    m = c[c.LSAD == "M1"].copy()             # M1 is a metro, M2 a micro area
    m["pop"] = m.GEOID.map(pop)
    m = m.sort_values("pop", ascending=False)
    # A metro qualifies on its own population, or as the largest metro in a
    # combined statistical area that reaches the floor.  The second clause is
    # not generosity, it is a correction: the 2023 delineation split St.
    # Tammany Parish out of New Orleans into a metro of its own, which dropped
    # New Orleans-Metairie to 988,763 and off a map of million-person metros.
    # The city did not shrink, the boundary moved, and its combined area is
    # 1,360,113.  Reading the CSA for the metro that leads it puts that class
    # of split right wherever it has happened -- fifteen metros in all, among
    # them Greensboro, Allentown, Dayton and Baton Rouge -- rather than
    # special-casing the one that was noticed.  "Largest in the CSA" is what
    # keeps Slidell from qualifying on New Orleans' size.
    lead = m.groupby("CSAFP", dropna=True).head(1).GEOID
    m["csa"] = m.CSAFP.map(csa)
    m = m[(m["pop"] >= floor)
          | (m.GEOID.isin(lead) & (m["csa"].fillna(0) >= floor))]
    m["primary"] = [re.split(r"[-,]", s)[0].strip() for s in m.NAME]

    g = gpd.read_file(f"zip://{IN / 'ne_10m_populated_places.zip'}")
    g = g[g.ADM0_A3 == "USA"].to_crs(ALBERS)
    g["key"] = [norm(s) for s in g.NAME]
    j = gpd.sjoin(g, m[["GEOID", "primary", "geometry"]], predicate="within")

    _METRO_CACHE["shapes"] = m[["GEOID", "NAME", "pop", "geometry"]]
    out = []
    for _, r in m.iterrows():
        sub = j[j.GEOID == r.GEOID]
        big = sub.sort_values("POP_MAX", ascending=False)
        hit = sub[sub.key == norm(r.primary)]
        # The fallback covers the odd title as well as the missing match: the
        # Census now calls the Poughkeepsie area "Kiryas Joel-Poughkeepsie-
        # Newburgh", after a village of 35,000 that Natural Earth does not
        # carry at all, so the name simply fails to match and the largest place
        # in the metro wins.  An earlier version also demoted any primary city
        # smaller than a tenth of its metro, which was unnecessary for that
        # case and wrong for Riverside -- 297,554 against a metro of 4.65m --
        # where it put San Bernardino's name on the Inland Empire.
        if not len(hit):
            hit = big
        if not len(hit):
            continue                          # San Juan: no place in the file
        p = hit.iloc[0]
        out.append((p.NAME, p.geometry.x, p.geometry.y))
    return out


def cities(geo, n):
    """Place names, carried through the flow like everything else.

    Without them a deformed map is unreadable; with them it is obvious that the
    swollen parts are the cities.

    They come out in metro-population order, and the page reveals them as the
    zoom makes room: see _town_zoom, which is what decides when each is seen.

    The million-person floor is a continental rule and does not survive being
    carried onto a 220 km window, where it left New York with one name on the
    page and the Bay Area with three.  A metro cut is already inside a single
    metropolitan area, so every metro in view earns its name there; what stays
    constant across the cuts is that a name means a metro area, which is the
    part that matters.
    """
    floor = MIN_METRO if geo["window"] is None else 0.0
    out = [t for t in _metros(floor)
           if geo["x0"] <= t[1] <= geo["x0"] + geo["tx"] * geo["side"]
           and geo["y1"] - geo["ty"] * geo["side"] <= t[2] <= geo["y1"]][:n]
    print(f"  {len(out)} metro areas"
          + (f" over {floor:,.0f} people" if floor else "")
          + " in this cut, named at their largest city")
    return ([t[0] for t in out],
            np.array([[t[1], t[2]] for t in out], dtype=float).reshape(-1, 2))


OFFSHORE = ["AK", "HI", "PR", "VI", "GU", "MP", "AS"]


def _outlines():
    """State polygons, at the best resolution on disk.

    Census cartographic boundaries at 1:500,000 are clipped to the shoreline
    and carry about five times the vertices of Natural Earth's 1:10m, which
    matters as soon as the map is zoomed: at 10m a bay a few kilometres across
    is a straight line.  Natural Earth stays as the fallback so the figures
    still build from an older inputs directory.
    """
    tiger = IN / "cb_2023_us_state_500k.zip"
    if tiger.exists():
        g = gpd.read_file(f"zip://{tiger}")
        g = g[~g.STUSPS.isin(OFFSHORE)].to_crs(ALBERS)
        return g.rename(columns={"NAME": "name", "STUSPS": "postal"})[
            ["name", "postal", "geometry"]].reset_index(drop=True)
    g = gpd.read_file(f"zip://{IN / 'ne_10m_admin_1_states_provinces.zip'}")
    g = g[(g.admin == "United States of America")
          & ~g.name.isin(["Alaska", "Hawaii"])].to_crs(ALBERS)
    return g[["name", "postal", "geometry"]].reset_index(drop=True)


def state_borders(geo, flat=False, cell=None):
    """State outlines clipped to whatever the map covers.

    On a metro cut the outlines are mostly a coastline; they are here so that
    the eye has something to hold on to once the tiles have moved.

    Two tolerances are at work, and they are set from different things.

    The simplify tolerance is what survives into the drawing, so it is set from
    the finest pixel the page can show: the map is drawn 2,000 px wide and
    zooms to 400x, which on the continental cut is 5.8 m to the pixel.  Tying
    it to the tile size instead put it at 250 m, which is a quarter of a pixel
    at full extent but forty-three pixels at full zoom -- so every bay and
    river bend on the page was a chord several pixels wide as soon as anyone
    looked closely.  The floor of 5 m is there because the source is drawn at
    1:500,000 and inventing detail below its own accuracy would be a lie; on
    the metro cuts the arithmetic asks for 0.3 m and gets the floor.

    On a cartogram there is a second floor, and it is coarser.  The outline is
    not drawn where it is: it is carried by a flow solved on a fixed grid, one
    cell of which is about a kilometre on the continental cut.  Detail finer
    than that cell is not transported, it is sheared -- neighbouring vertices
    of the same bay get pulled by the same interpolated vector, so a coastline
    resolved to 5 m arrives on the page as a tangle of crossing hairs, and a
    5 m tolerance simply buys more hairs.  Half a cell is as fine as the
    deformation can honestly carry.  The flat cuts keep the pixel tolerance,
    because nothing moves there and the detail is real.

    The densify tolerance is a different quantity and must not follow it.  It
    only matters on a cartogram, where a straight state line has to bend with
    the flow, so it is set from the tile size -- the scale at which the flow
    itself varies.  Chaining it to the simplify tolerance, as an earlier
    version did, would now insert a vertex every 200 m along the straight
    western borders for no gain at all.  On a flat cut nothing bends, so it is
    skipped.
    """
    box = shapely.geometry.box(
        geo["x0"], geo["y1"] - geo["ty"] * geo["side"],
        geo["x0"] + geo["tx"] * geo["side"], geo["y1"])
    g = _outlines()
    g["geometry"] = g.geometry.intersection(box)
    g = g[~g.geometry.is_empty & (g.geometry.area > 0)].reset_index(drop=True)
    tol = max(geo["tx"] * geo["side"] / DRAW_W / MAX_ZOOM, 5.0)
    if not flat and cell:
        tol = max(tol, cell / 2.0)
    g["geometry"] = [q.simplify(tol).buffer(0) for q in g.geometry]
    if not flat:
        g["geometry"] = [densify(q, max(geo["side"], 2000.0))
                         for q in g.geometry]
    # Aligned to the polygons, DC included, because the ring index is what
    # names them once they are drawn: see _drawn_anchors, which finds the
    # anchor on the deformed shape rather than carrying one through the flow.
    return g, g.postal.tolist()


# --- the flow -------------------------------------------------------------

def cached(key, r, field, extent, pts, quads, tile_value):
    """The flow is the expensive part and the drawing is the part worth
    iterating on, so the transported points are kept on disk.

    The name carries a digest of the density field as well as the settings.
    Matching on shape alone was not enough: rebuilding the GDP surface with a
    different allocation leaves the same tiles occupied and the same number of
    vertices, so a stale mesh would have been served silently for a density it
    was never solved against.
    """
    CACHE.mkdir(parents=True, exist_ok=True)
    k = r["mesh"] or key
    h = hashlib.blake2b(np.ascontiguousarray(field, dtype="<f8").tobytes(),
                        digest_size=6).hexdigest()
    f = CACHE / f"{k}_b{r['block']}_n{r['nx']}_p{r['passes']}_s{STEPS}_{h}.npy"
    if f.exists():
        moved = np.load(f)
        if moved.shape == pts.shape:
            print(f"  (reusing {f.name})")
            return moved
    moved = relax(field, extent, pts, quads, tile_value, r["nx"],
                  r["passes"])
    np.save(f, moved)
    return moved



def relax(field, extent, pts, quads, tile_value, NX, passes):
    """Diffuse, redraw, diffuse again.

    A single diffusion pass can equalise a density range of maybe fifty to one.
    Here it is a million to one, so the first pass gets the continental
    structure right and leaves the cities short.  Feeding the deformed map back
    in as the new density picks up most of what is left; the check below prints
    what each pass bought.
    """
    x0, x1, y0, y1 = extent
    ny = field.shape[0]
    tr = from_bounds(x0, y0, x1, y1, NX, ny)
    share_v = tile_value / tile_value.sum()
    p = pts.copy()
    for i in range(passes):
        cg = DiffusionCartogram(np.flipud(field), extent, blur=0.8)
        p = cg.transform(p, n_steps=STEPS, t_end=6.0 / cg.decay[0, 1])
        areas = _areas(p, quads)
        good = areas > 0
        share_a = areas / areas[good].sum()
        err = np.abs(share_a[good] / share_v[good] - 1)
        print(f"  pass {i+1}: median |area error| {np.median(err):.1%}, "
              f"90th percentile {np.percentile(err, 90):.1%}")
        if i == passes - 1:
            break
        shapes = [(Polygon(p[q]).buffer(0), v / max(a, 1e-9))
                  for q, a, v in zip(quads, areas, tile_value) if a > 0]
        nxt = rasterize(shapes, out_shape=(ny, NX), transform=tr, fill=0.0,
                        dtype="float64", all_touched=True)
        hit = nxt > 0
        field = np.where(hit, nxt, nxt[hit].mean())
    return p


def _areas(p, quads):
    """Shoelace over every quad at once."""
    r = p[quads]                                   # (n, 4, 2)
    s = np.roll(r, -1, axis=1)
    return 0.5 * np.abs((r[:, :, 0] * s[:, :, 1] - s[:, :, 0] * r[:, :, 1]).sum(1))


# --- drawing --------------------------------------------------------------

def _scene(r, geo, tiles, quads, moved, n_lattice, bidx, postal, city_name,
           lab0, real, tile_value, areas, midx=()):
    """Everything both pages need: the drawing box, the colours, the payload.

    The document figure and the scrolled story draw the same tiles with the
    same scale from the same buffers.  They share this function so that a
    change to either can never leave them showing different maps.
    """
    base = span = None
    lat = moved[:n_lattice]
    bx0, by0 = moved.min(0)
    bx1, by1 = moved.max(0)
    span = max(bx1 - bx0, by1 - by0)
    pad = 0.01 * span
    bx0, by0, bx1, by1 = bx0 - pad, by0 - pad, bx1 + pad, by1 + pad
    span = max(bx1 - bx0, by1 - by0)
    W = DRAW_W
    H = W * (by1 - by0) / (bx1 - bx0)

    def to_px(a):
        return np.stack([(a[:, 0] - bx0) / (bx1 - bx0) * W,
                         H - (a[:, 1] - by0) / (by1 - by0) * H], axis=1)

    # Vertices go out quantised to 16 bits over the drawing box: 2000 px of
    # map in 65,536 steps, which is a thirtieth of a pixel.
    px = to_px(lat)
    qx = np.clip(np.round(px[:, 0] / W * 65535), 0, 65535).astype("<u2")
    qy = np.clip(np.round(px[:, 1] / H * 65535), 0, 65535).astype("<u2")

    # Colour is continuous in log price and stretched to whatever this cut
    # happens to span.  A fixed national scale collapses a single metro into
    # one shade, because within one metro the range is a factor of a hundred,
    # not a factor of a million.
    side_km2 = (geo["side"] / 1000.0) ** 2
    density = tile_value / side_km2
    logd = np.log10(np.maximum(density, 1.0))
    gdp = _gdp_tiles(geo).ravel()[tiles] if r["diverge"] else None
    # Weighted by value, not by tile count.  On a cartogram a tile's share of
    # the page *is* its share of value, so a scale set on the unweighted
    # distribution spends most of its range on tiles too small to see and the
    # visible map comes out one flat colour.
    if r["diverge"]:
        # Every tile's own land-to-output ratio against the national one.  The
        # scale is symmetric in log so the midpoint is the baseline exactly and
        # a factor of ten either way is the same distance from it.
        base = tile_value.sum() / gdp.sum()
        # Only ground with a workplace on it gets a colour.  Everywhere else
        # the output is county GDP spread by population and land cover, whose
        # rates are constant inside a county by construction: 73% of the
        # variance of the ratio on that ground is between counties rather than
        # within them, against 25% where there are jobs.  Drawing it at 3.84 km
        # claims a resolution the denominator does not have, and it claimed it
        # as county rectangles.  It is drawn in one flat colour instead.
        fine = _gdp_tiles(geo, kinds=(0,)).ravel()[tiles]
        has = (gdp > 0) & (fine > 0)
        lr = np.zeros(len(tile_value))
        lr[has] = np.log10((tile_value[has] / gdp[has]) / base)
        a, b = _wpct(lr[has], tile_value[has], [2, 98])
        span = min(max(abs(a), abs(b)), 2.5)
        print(f"  baseline {base:.4f} years of output; colour spans "
              f"1/{10**span:,.0f}x to {10**span:,.0f}x of it")
        print(f"  {int((~has & real).sum()):,d} tiles have no workplace on "
              "them, so their output is known only by county and they are not "
              f"given a ratio ({tile_value[~has & real].sum()/tile_value[real].sum():.1%}"
              " of the land value on the page)")
        # What the coloured ground says, weighted by land value -- the same
        # weighting the scale uses, and the numbers the write-up quotes, so
        # they are regenerated on every build rather than typed once.
        col = has & real
        p10, p50, p90 = _wpct(lr[col], tile_value[col], [10, 50, 90])
        dear = tile_value[col][lr[col] > 0].sum() / tile_value[col].sum()
        print(f"  of the coloured ground, the median dollar of land value sits "
              f"on {base * 10**p50:.3f} years of its own output "
              f"({base * 10**p10:.3f} at the 10th, {base * 10**p90:.1f} at the "
              f"90th); {dear:.1%} of it is dearer than the baseline")
        u = np.clip(np.round((lr / span + 1) / 2 * 254), 0, 254).astype("u1")
        u[~has] = 255                      # the sentinel the browser paints grey
        lo, hi = -span, span
    else:
        lo, hi = _wpct(logd[real], tile_value[real], [2, 99.5])
        print(f"  colour runs ${10**lo:,.0f} to ${10**hi:,.0f} per km2 "
              f"(2nd to 99.5th percentile of the page, by area)")
        u = np.clip(np.round((logd - lo) / max(hi - lo, 1e-9) * 255),
                    0, 255).astype("u1")
    # tooltip payload: log10 of dollars, in units of 1/4096
    vq = np.clip(np.round((np.log10(np.maximum(tile_value, 1.0)) - 3) * 4096),
                 0, 65535).astype("<u2")

    # Only the real tiles are shipped; the floor tiles did their work in the
    # flow and have no business in the picture.
    draw = np.nonzero(real & (areas > 0))[0]
    blobs = {
        "vx": qx.tobytes(), "vy": qy.tobytes(),
        "quads": quads[draw].astype("<u4").tobytes(),
        "u": u[draw].tobytes(), "val": vq[draw].tobytes(),
    }
    if r["diverge"]:
        g2 = np.clip(np.round((np.log10(np.maximum(gdp, 1.0)) - 3) * 4096),
                     0, 65535).astype("<u2")
        blobs["val2"] = g2[draw].tobytes()
    payload = {k: _b64(v) for k, v in blobs.items()}

    borders, big = [], {}
    for i, start, n in bidx:
        ring = to_px(moved[start:start + n])
        if len(ring) < 4:
            continue
        # Keep each state's largest drawn ring, to hang its name on below.
        a = 0.5 * abs(float(np.dot(ring[:, 0], np.roll(ring[:, 1], -1))
                            - np.dot(ring[:, 1], np.roll(ring[:, 0], -1))))
        if i not in big or a > big[i][0]:
            big[i] = (a, ring)
        # Three decimals, not one.  The path is drawn inside an SVG scaled by
        # the zoom, so a coordinate rounded to a tenth of a pixel at full
        # extent is rounded to forty pixels at 400x: the outline came apart
        # into visible steps exactly where the extra vertices above are meant
        # to be showing detail.  Three decimals put that quantisation at 0.4 px
        # at the deepest zoom, which is below what the screen can resolve.
        borders.append("M" + "L".join(f"{x:.3f},{y:.3f}" for x, y in ring)
                       + "Z")
    metros = []
    for _, start, n in midx:
        ring = to_px(moved[start:start + n])
        if len(ring) < 4:
            continue
        metros.append("M" + "L".join(f"{x:.3f},{y:.3f}" for x, y in ring)
                      + "Z")
    cp = to_px(moved[lab0:])
    codes, lp = _drawn_anchors(big, postal)
    return dict(W=W, H=H, base=base, span=span, lo=lo, hi=hi, draw=draw,
                payload=payload, borders=borders, metros=metros,
                density=density,
                labels=[[q, round(float(x), 1), round(float(y), 1), k]
                        for (q, (x, y)), k in zip(zip(codes, lp),
                                                  _state_zoom(lp))],
                towns=[[q, round(float(x), 1), round(float(y), 1), k]
                       for (q, (x, y)), k in zip(zip(city_name, cp),
                                                 _town_zoom(cp))],
                bx=(bx0, by0, bx1, by1), to_px=to_px)


# How many names stand at full extent, and how much clear space each one wants,
# in drawing units.  A name is about 80 units wide at this font, so 70 tolerates
# a little overlap and relies on the halo behind the text for the rest.
TOWNS_AT_FULL = 60
TOWN_CLEAR = 40.0


def _drawn_anchors(big, postal):
    """A state's name goes in the middle of the shape the reader can see.

    The anchor used to be found on the undeformed state and then carried
    through the flow like everything else.  That is right for a dot -- a city
    is a place and it should move with its ground -- but wrong for a name that
    belongs to a whole shape.  A cartogram does not move a state rigidly: it
    inflates the cities inside it and squeezes the rest, so the point that was
    central before the flow can finish anywhere, and on this map several names
    ended up pressed against the edge of a state they were supposed to sit in.

    So it is measured after the fact instead, on the ring actually drawn: the
    pole of inaccessibility of the state's largest drawn part.  On a flat cut
    the drawn ring is the real shape and this gives the same answer as before,
    which is the check that it is the deformation being handled and not the
    projection.
    """
    out_c, out_p = [], []
    for i in sorted(big):
        if i >= len(postal) or postal[i] == "DC":
            continue                      # the city label already names it
        q = Polygon(big[i][1])
        if not q.is_valid:
            q = q.buffer(0)
            q = max(q.geoms, key=lambda z: z.area) if q.geom_type != "Polygon" \
                else q
        try:
            p = shapely.ops.polylabel(q, tolerance=1.0)
        except Exception:
            p = q.representative_point()
        out_c.append(postal[i])
        out_p.append([p.x, p.y])
    return out_c, np.array(out_p, dtype=float).reshape(-1, 2)


STATE_CLEAR = 30.0       # a two-letter code is about 25 drawing units wide


def _state_zoom(lp):
    """The zoom at which each state code appears.

    Unlike the city names these have no rank -- no state outranks another --
    so the rule is symmetric: a code waits until its nearest neighbouring code
    is `STATE_CLEAR` away on screen, and when two are too close *both* wait.
    Connecticut, Rhode Island and Massachusetts arrive together or not at all,
    which is easier to read than an arbitrary one of the three.

    Montana's nearest neighbour is far away, so it shows everywhere, including
    on a phone where the six New England codes do not.
    """
    if len(lp) < 2:
        return [0.0] * len(lp)
    out = []
    for i, p in enumerate(lp):
        d = np.hypot(*(lp - p).T)
        d[i] = np.inf
        out.append(round(float(STATE_CLEAR / max(float(d.min()), 1e-6)), 3))
    return out


def _town_zoom(cp):
    """The zoom at which each place name appears, from where the flow put it.

    Two things decide it and the later one wins.

    Rank: room on the page is an area, so the count that fits grows with the
    square of the zoom and the i-th name's turn comes at sqrt(i / 80).

    Separation: a name is unreadable if a bigger name is sitting on it, however
    high its rank.  So it also waits until the gap to the nearest larger place
    is worth `TOWN_CLEAR` on screen.  Measuring that on the *drawn* positions,
    after the flow, is the whole point: a cartogram pulls Oakland away from San
    Francisco, so on that map the two separate earlier than on the flat one,
    and the rule follows the map instead of second-guessing it.

    This is what keeps Natural Earth's agglomeration figures from embarrassing
    the map.  Its population for Irvine is the Anaheim-Santa Ana total, which
    ranks it fifteenth in the country -- above San Diego -- and it would sit on
    top of Los Angeles at full extent.  The separation term holds it back until
    there is room for it, without anyone having to curate a list of names.
    """
    out = []
    for i, p in enumerate(cp):
        by_rank = np.sqrt((i + 1) / TOWNS_AT_FULL)
        if i == 0:
            out.append(round(float(by_rank), 3))
            continue
        d = float(np.min(np.hypot(*(cp[:i] - p).T)))
        by_room = TOWN_CLEAR / max(d, 1e-6)
        out.append(round(float(max(by_rank, by_room)), 3))
    return out


def render(key, r, value, geo, tiles, quads, moved, n_lattice, bidx,
           postal, city_name, lab0, real, midx=()):
    FIG.mkdir(parents=True, exist_ok=True)
    tile_value = value.ravel()[tiles]
    areas = _areas(moved, quads)
    share_a_all = np.where(areas > 0, areas / areas[areas > 0].sum(), 0.0)
    flat = r["flat"]
    # Score only the tiles that will be drawn, against their share of the whole
    # quantity -- the floor tiles are part of the page even though they are not
    # part of the picture.
    good = (areas > 0) & real
    share_a = areas / areas[areas > 0].sum()
    share_v = tile_value / tile_value.sum()
    if flat:
        print("\nNo flow was run: every tile is drawn on the ground it "
              "occupies, so area carries no information and there is nothing "
              "to check.")
    else:
        err = share_a[good] / share_v[good] - 1
        order = np.argsort(-share_v[good])
        print(f"\nArea check -- each drawn tile's area against its share of "
              f"{r['quantity']}")
        print(f"  median |error| {np.median(np.abs(err)):.1%}; "
              f"across the 2,000 most valuable tiles "
              f"{np.median(np.abs(err[order[:2000]])):.1%}")
        print(f"  value-weighted mean |error| "
              f"{np.average(np.abs(err), weights=share_v[good]):.1%}; "
              f"correlation of drawn area with value "
              f"{np.corrcoef(share_a[good], share_v[good])[0,1]:.4f}")

    s = _scene(r, geo, tiles, quads, moved, n_lattice, bidx, postal,
               city_name, lab0, real, tile_value, areas, midx=midx)
    W, H = s["W"], s["H"]
    base, span, lo, hi = s["base"], s["span"], s["lo"], s["hi"]
    draw, payload, borders = s["draw"], s["payload"], s["borders"]
    density = s["density"]

    check = pd.DataFrame({
        "tile_row": tiles[real] // geo["tx"], "tile_col": tiles[real] % geo["tx"],
        "value_usd": np.round(tile_value[real]).astype("int64"),
        "usd_per_km2": np.round(density[real]).astype("int64"),
        "drawn_area_share": share_a_all[real],
    })
    # Half a million rows; gzipped, because the point of shipping it is that
    # every tile can be audited, not that it be convenient to open.
    check.sort_values("value_usd", ascending=False).to_csv(
        DATA / f"us_cartogram_check_{key}.csv.gz", index=False,
        float_format="%.3e")

    tot = tile_value[real].sum()
    money = (f"${tot/1e12:,.2f} trillion" if tot >= 1e12
             else f"${tot/1e9:,.0f} billion")
    side = geo["side"] / 1000.0
    html = _HTML.format(
        W=f"{W:.0f}", H=f"{H:.0f}", maxk=f"{MAX_ZOOM:.0f}",
        title=_esc(r["title"]), where=_esc(r["where"]),
        provenance=PROVENANCE["ratio" if r["diverge"] else r["src"]],
        lede=(f"Every square is the same {side:.2f} km of real ground, drawn "
              f"where it actually is. The colour is one number: what the land "
              f"in that square is worth, divided by the output produced on it "
              f"in a year &mdash; a price-to-earnings ratio for the ground, "
              f"measured in years. {len(draw):,d} tiles covering "
              f"{_esc(r['where'])}, holding {money} of land value."
              if r["flat"] else
              f"Every square is the same {side:.2f} km of real ground; its "
              f"size on the page is its share of the {money} of "
              f"{_esc(r['quantity'])} in {_esc(r['where'])}. {len(draw):,d} "
              f"tiles." + (" The colour is one number: what the land in that "
                           "square is worth, divided by the output produced on "
                           "it in a year &mdash; a price-to-earnings ratio for "
                           "the ground, measured in years."
                           if r["diverge"] else "")),
        n=len(draw),
        km2=f"{side*side:.6f}",
        metros=json.dumps(s["metros"]),
        data=json.dumps(payload), base=f"{base:.6f}" if r["diverge"] else "1",
        borders=json.dumps(borders),
        labels=json.dumps(s["labels"]), towns=json.dumps(s["towns"]),
        ramp=json.dumps(DIVERGE if r["diverge"] else RAMP),
        noval=json.dumps(NOVAL if r["diverge"] else None),
        legend=(_legend_diverge(span, base) if r["diverge"]
                else _legend(lo, hi, r["caption"])),
        noun=_esc(r["noun"]), colour=r["colour"], notes=r["notes"],
    )
    stem = ("land_vs_output_map" if r["flat"]
            else "land_vs_output_cartogram" if r["diverge"]
            else "land_value_cartogram" if r["src"] == "land"
            else "gdp_cartogram")
    out = FIG / f"{stem}_{key.replace('gdp', '').replace('ratioflat', '').replace('ratio', '')}.html"
    out.write_text(html, encoding="utf-8")
    print(f"\n-> docs/figures/{out.name} ({len(draw):,d} tiles drawn, "
          f"{len(html)/1e6:.1f} MB)")


def _wpct(x, w, qs):
    o = np.argsort(x)
    c = np.cumsum(w[o])
    c = (c - 0.5 * w[o]) / c[-1] * 100
    return np.interp(qs, c, x[o])


def _b64(b):
    return base64.b64encode(zlib.compress(b, 6)).decode("ascii")


def _legend(lo, hi, caption):
    """A continuous bar with five priced ticks, in dollars per square km."""
    stops = ", ".join(f"{c} {i/(len(RAMP)-1)*100:.0f}%"
                      for i, c in enumerate(RAMP))
    ticks = "".join(
        f'<span>{_money(10 ** (lo + (hi - lo) * f))}</span>'
        for f in (0, 0.25, 0.5, 0.75, 1))
    return (f'<div class="bar" style="background:linear-gradient(90deg,{stops})">'
            f'</div><div class="ticks">{ticks}</div>'
            f'<div class="cap">{caption}</div>')


def _legend_diverge(span, base):
    """A two-sided bar: how far the ground departs from the national ratio."""
    stops = ", ".join(f"{c} {i/(len(DIVERGE)-1)*100:.0f}%"
                      for i, c in enumerate(DIVERGE))
    # Both readings on the same bar: the multiple of the national figure, and
    # the years the multiple works out to, so nobody has to do the arithmetic.
    def _yr(x):
        if x >= 1:
            return f"{x:,.0f} year" + ("" if round(x) == 1 else "s")
        d = x * 365
        return "under a day" if d < 0.5 else f"{d:,.0f} day" + ("" if round(d) == 1 else "s")
    ticks = "".join(
        f"<span>{m}<br><i>{_yr(base * f)}</i></span>" for m, f in
        ((f"1/{10**span:,.0f}&times;", 10 ** -span),
         (f"1/{10**(span/2):,.0f}&times;", 10 ** (-span / 2)),
         ("the U.S. figure", 1.0),
         (f"{10**(span/2):,.0f}&times;", 10 ** (span / 2)),
         (f"{10**span:,.0f}&times;", 10 ** span)))
    return (f'<div class="bar" style="background:linear-gradient(90deg,{stops})">'
            f'</div><div class="ticks yrs">{ticks}</div>'
            f'<div class="cap"><b>Land value &divide; a year of the output '
            f'produced on it</b>, against the national figure of '
            f'{base:.2f} years &mdash; that is, all the land in the lower 48 is '
            f'worth about {base*12:.0f} months of what is made on it.<br>'
            f'<b style="color:#35978f">Teal</b>: the ground is cheap for the '
            f'work it carries. <b style="color:#8c510a">Brown</b>: the ground '
            f'costs more than the work on it accounts for. '
            f'<i style="background:{NOVAL};width:11px;height:11px;'
            f'display:inline-block;border-radius:2px;vertical-align:-1px"></i> '
            f'grey: no workplace here, so the output is known only by '
            f'county and no ratio is drawn.</div>')


def _money(x):
    if x >= 1e9:
        return f"${x/1e9:,.0f}bn"
    if x >= 1e6:
        return f"${x/1e6:,.0f}m"
    return f"${x/1e3:,.0f}k"


_GL_JS = """const W={W}, H={H}, NT={n}, KM2={km2}, BASE={base}, MAXK={maxk};
const RAMP={ramp}, NOVAL={noval};
const D={data};
const BORDERS={borders}, METROS={metros}, LABELS={labels}, TOWNS={towns};

// The geometry travels deflated; the browser's own decompressor unpacks it,
// so everything below waits on a promise.
async function unz(b64) {{
  const s = atob(b64), n = s.length, u = new Uint8Array(n);
  for (let i=0;i<n;i++) u[i]=s.charCodeAt(i);
  const ds = new DecompressionStream('deflate');
  const buf = await new Response(
    new Blob([u]).stream().pipeThrough(ds)).arrayBuffer();
  return new Uint8Array(buf);
}}

const cv=document.getElementById('cv'), stage=document.getElementById('stage');
// ?shot keeps the drawing buffer around so a headless browser can
// screenshot the canvas; without it the capture races the compositor and
// comes back empty.  Off by default, because preserving it costs memory.
const gl=cv.getContext('webgl2',{{antialias:true,alpha:true,
  preserveDrawingBuffer:location.search.indexOf('shot')>=0}});
const ov=document.getElementById('ov'), sc=document.getElementById('sc');
const tip=document.getElementById('tip'), hud=document.getElementById('hud');

document.getElementById('bd').innerHTML =
  BORDERS.map(d=>`<path class="sb" d="${{d}}"/>`).join('');
const _mb=document.getElementById('mb');
// Casing first, then the dashes, so every ring is legible wherever it crosses
// a dark tile -- two passes rather than one path each, to keep all the casing
// underneath all the dashes where rings touch.
if(_mb) _mb.innerHTML =
  METROS.map(d=>`<path class="mrc" d="${{d}}"/>`).join('')
  + METROS.map(d=>`<path class="mr" d="${{d}}"/>`).join('');
document.getElementById('lb').innerHTML =
  LABELS.map(l=>`<text class="sl" data-k="${{l[3]}}" x="${{l[1]}}" `+
    `y="${{l[2]}}">${{l[0]}}</text>`).join('');
// Each place carries the zoom at which it appears, worked out in
// _town_zoom() from where the flow actually put it.  Deriving it here from the
// rank alone could not see the drawn positions, so it had no way to know that
// two names were on top of each other.
document.getElementById('tw').innerHTML =
  TOWNS.map(l=>`<g class="tg" data-k="${{l[3]}}">`+
    `<circle class="td" cx="${{l[1]}}" cy="${{l[2]}}" r="2"/>`+
    `<text class="tn" x="${{l[1]}}" y="${{l[2]}}" dy="-0.7em">${{l[0]}}</text></g>`)
    .join('');

const VS=`#version 300 es
in vec2 a_pos; in vec3 a_col; in vec3 a_id;
uniform vec2 u_size; uniform float u_k; uniform vec2 u_o; uniform float u_pick;
out vec3 v_col;
void main() {{
  vec2 p = a_pos * u_k + u_o;
  gl_Position = vec4(p.x/u_size.x*2.0-1.0, 1.0-p.y/u_size.y*2.0, 0.0, 1.0);
  v_col = mix(a_col, a_id, u_pick);
}}`;
const FS=`#version 300 es
precision highp float; in vec3 v_col; out vec4 o;
void main() {{ o = vec4(v_col, 1.0); }}`;

function sh(t,s) {{ const x=gl.createShader(t); gl.shaderSource(x,s);
  gl.compileShader(x);
  if(!gl.getShaderParameter(x,gl.COMPILE_STATUS)) throw gl.getShaderInfoLog(x);
  return x; }}
const prog=gl.createProgram();
gl.attachShader(prog,sh(gl.VERTEX_SHADER,VS));
gl.attachShader(prog,sh(gl.FRAGMENT_SHADER,FS));
gl.linkProgram(prog); gl.useProgram(prog);
const uSize=gl.getUniformLocation(prog,'u_size');
const uK=gl.getUniformLocation(prog,'u_k'), uO=gl.getUniformLocation(prog,'u_o');
const uPick=gl.getUniformLocation(prog,'u_pick');

let view={{k:1,ox:0,oy:0}}, count=0, ready=false, fb=null, ftex=null;
let TVAL=null, TU=null, TGDP=null;

(async function build() {{
  const [vxb, vyb, qb, bb, vb] = await Promise.all(
    [D.vx, D.vy, D.quads, D.u, D.val].map(unz));
  if (D.val2) TGDP = new Uint16Array((await unz(D.val2)).buffer);
  const vx=new Uint16Array(vxb.buffer), vy=new Uint16Array(vyb.buffer);
  const quads=new Uint32Array(qb.buffer);
  TU=bb; TVAL=new Uint16Array(vb.buffer);

  // Corners are shared in the file and expanded here, because each tile needs
  // its own colour and a shared vertex cannot carry two.
  const pos=new Float32Array(NT*8), col=new Uint8Array(NT*12);
  const idc=new Uint8Array(NT*12), idx=new Uint32Array(NT*6);
  // 256 shades interpolated between the ramp's stops, so the scale is
  // continuous rather than a staircase.
  const stops=RAMP.map(h=>[parseInt(h.slice(1,3),16),parseInt(h.slice(3,5),16),
                           parseInt(h.slice(5,7),16)]);
  const rgb=new Array(256);
  const top=NOVAL?254:255;
  for(let i=0;i<=top;i++) {{
    const f=i/top*(stops.length-1), a=Math.min(Math.floor(f),stops.length-2);
    const g=f-a;
    rgb[i]=[0,1,2].map(j=>Math.round(stops[a][j]+(stops[a+1][j]-stops[a][j])*g));
  }}
  // 255 is the sentinel for land with no workplace on it, not the top of a scale.
  if(NOVAL) rgb[255]=[1,3,5].map(k=>parseInt(NOVAL.slice(k,k+2),16));
  for(let t=0;t<NT;t++) {{
    const c=rgb[TU[t]], id=t+1;
    const r=(id&255), g=((id>>8)&255), b=((id>>16)&255);
    for(let j=0;j<4;j++) {{
      const v=quads[t*4+j], o=(t*4+j);
      pos[o*2]=vx[v]/65535*W; pos[o*2+1]=vy[v]/65535*H;
      col[o*3]=c[0]; col[o*3+1]=c[1]; col[o*3+2]=c[2];
      idc[o*3]=r; idc[o*3+1]=g; idc[o*3+2]=b;
    }}
    const b0=t*4;
    idx[t*6]=b0; idx[t*6+1]=b0+1; idx[t*6+2]=b0+2;
    idx[t*6+3]=b0; idx[t*6+4]=b0+2; idx[t*6+5]=b0+3;
  }}
  count=NT*6;

  const vao=gl.createVertexArray(); gl.bindVertexArray(vao);
  function buf(data, loc, size, type, norm) {{
    const b=gl.createBuffer(); gl.bindBuffer(gl.ARRAY_BUFFER,b);
    gl.bufferData(gl.ARRAY_BUFFER,data,gl.STATIC_DRAW);
    const l=gl.getAttribLocation(prog,loc);
    gl.enableVertexAttribArray(l);
    gl.vertexAttribPointer(l,size,type,norm,0,0);
  }}
  buf(pos,'a_pos',2,gl.FLOAT,false);
  buf(col,'a_col',3,gl.UNSIGNED_BYTE,true);
  buf(idc,'a_id',3,gl.UNSIGNED_BYTE,true);
  const ib=gl.createBuffer();
  gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,ib);
  gl.bufferData(gl.ELEMENT_ARRAY_BUFFER,idx,gl.STATIC_DRAW);
  ready=true; resize();
}})();"""


_HTML = """<!doctype html>
<meta charset="utf-8">
<title>{title}</title>
<meta name="viewport" content="width=device-width,initial-scale=1">
<style>
:root {{
  color-scheme: light dark;
  --ink: #14171a; --muted: #5b6570; --bg: #ffffff; --line: #d8dee6;
  --panel: #f6f8fa;
}}
@media (prefers-color-scheme: dark) {{
  :root {{ --ink:#e8ecf1; --muted:#9aa6b2; --bg:#0f1216; --line:#2a323c;
           --panel:#171c22; }}
}}
:root[data-theme="dark"] {{ --ink:#e8ecf1; --muted:#9aa6b2; --bg:#0f1216;
  --line:#2a323c; --panel:#171c22; }}
:root[data-theme="light"] {{ --ink:#14171a; --muted:#5b6570; --bg:#ffffff;
  --line:#d8dee6; --panel:#f6f8fa; }}
/* The map keeps its own ground and its own ink in both themes.  Everything
   drawn over the tiles -- outlines, name halos, town dots -- is keyed to
   these rather than to the page, so the figure does not invert under it. */
:root {{ --mapbg:#ffffff; --mapink:#14171a; }}
* {{ box-sizing: border-box; }}
body {{ margin:0; background:var(--bg); color:var(--ink);
  font:15px/1.5 ui-sans-serif,-apple-system,"Segoe UI",Roboto,sans-serif; }}
.wrap {{ max-width:1180px; margin:0 auto; padding:28px 20px 56px; }}
h1 {{ font-size:26px; margin:0 0 6px; letter-spacing:-0.01em; }}
p.sub {{ margin:0 0 18px; color:var(--muted); max-width:70ch; }}
#stage {{ position:relative; width:100%; aspect-ratio:{W} / {H};
  border:1px solid var(--line); border-radius:10px; overflow:hidden;
  background:var(--mapbg); touch-action:none; cursor:grab; }}
#stage.drag {{ cursor:grabbing; }}
canvas, svg.ov {{ position:absolute; inset:0; width:100%; height:100%; }}
/* The tiles are the evidence but the coast is how the eye finds its place, so
   the data layer is held back far enough for the outlines to sit on top of it
   rather than fight it.  The stage keeps a light ground under the canvas in
   either theme: black lines over a dimmed dark map would be invisible. */
canvas {{ opacity:.74; }}
svg.ov {{ pointer-events:none; }}
.sb {{ fill:none; stroke:#000; stroke-opacity:.62; stroke-width:.9;
  vector-effect:non-scaling-stroke; stroke-linejoin:round; }}
/* State codes are orientation, not content: they should be findable when the
   eye goes looking and invisible when it is reading the tiles.  The city names
   sit above them in both size and weight. */
.sl {{ fill:var(--mapink); fill-opacity:.5; font-size:11px; font-weight:600;
  text-anchor:middle; paint-order:stroke; stroke:var(--mapbg);
  stroke-opacity:.7; stroke-width:2.6px; stroke-linejoin:round; }}
@media (prefers-reduced-motion: reduce) {{ #tip {{ transition:none; }} }}
#tip {{ position:absolute; pointer-events:none; background:var(--bg);
  border:1px solid var(--line); border-radius:6px; padding:6px 9px;
  font-size:13px; box-shadow:0 2px 10px rgba(0,0,0,.14); opacity:0;
  transition:opacity .1s; white-space:nowrap; }}
#hud {{ position:absolute; left:10px; bottom:10px; font-size:12px;
  font-variant-numeric:tabular-nums;
  color:var(--muted); background:var(--bg); border:1px solid var(--line);
  border-radius:6px; padding:4px 8px; }}
/* A row under the map.  Both controls are sized for a finger -- 38px is the
   smallest target that is reliably hit on a phone -- and neither overlaps the
   figure, so nothing has to be dodged to read the map underneath. */
.ctl {{ display:flex; flex-wrap:wrap; align-items:center; gap:8px;
  margin-top:10px; }}
.ctl button {{ font:inherit; font-size:13px; min-height:38px; padding:0 14px;
  border:1px solid var(--line); border-radius:8px;
  background:var(--bg); color:var(--ink); cursor:pointer;
  touch-action:manipulation; user-select:none; -webkit-user-select:none; }}
.ctl button:focus-visible {{ outline:2px solid currentColor;
  outline-offset:2px; }}
/* A switch rather than a button: a plain button that toggles a layer gives the
   reader no way to tell, before clicking, that it is a two-state control, and
   no way to tell afterwards which state it left behind. */
#metros {{ display:flex; align-items:center; gap:8px; padding:0 14px 0 10px;
  color:var(--muted); }}
#metros .tr {{ display:block; width:32px; height:18px; border-radius:9px;
  background:var(--line); position:relative; transition:background .12s;
  flex:none; }}
#metros .kn {{ position:absolute; top:2px; left:2px; width:14px; height:14px;
  border-radius:50%; background:var(--bg); transition:left .12s;
  box-shadow:0 1px 2px rgba(0,0,0,.3); }}
#metros[aria-checked="true"] {{ color:var(--ink); border-color:currentColor; }}
#metros[aria-checked="true"] .tr {{ background:currentColor; }}
#metros[aria-checked="true"] .kn {{ left:16px; }}
@media (prefers-reduced-motion: reduce) {{
  #metros .tr, #metros .kn {{ transition:none; }}
}}
/* Off by default: the metro outlines answer a question the reader has to ask.
   Dashed and thinner than a state line, so that when both are on it is obvious
   which is which -- but laid over a white casing, because at country zoom a
   hairline dash on top of the tiles is not visible enough to read as a change. */
#mb {{ visibility:hidden; }}
#mb.on {{ visibility:visible; }}
.mrc {{ fill:none; stroke:var(--mapbg); stroke-opacity:.9; stroke-width:3.6;
  vector-effect:non-scaling-stroke; stroke-linejoin:round; }}
.mr {{ fill:none; stroke:#000; stroke-opacity:.9; stroke-width:1.6;
  stroke-dasharray:6 4; vector-effect:non-scaling-stroke;
  stroke-linejoin:round; }}
.legend {{ margin:14px 0 0; max-width:520px; }}
.bar {{ height:11px; border-radius:3px; }}
.ticks {{ display:flex; justify-content:space-between; font-size:11px;
  font-variant-numeric:tabular-nums;
  color:var(--muted); margin-top:4px; }}
.cap {{ font-size:12px; color:var(--muted); margin-top:2px; line-height:1.5; }}
.legend {{ max-width:640px; }}
.ticks.yrs span {{ text-align:center; }}
.ticks.yrs span:first-child {{ text-align:left; }}
.ticks.yrs span:last-child {{ text-align:right; }}
.ticks.yrs i {{ font-style:normal; opacity:.62; }}
.tn {{ fill:var(--mapink); font-size:12px; font-weight:600; text-anchor:middle;
  paint-order:stroke; stroke:var(--mapbg); stroke-width:3.5px;
  stroke-linejoin:round; }}
.td {{ fill:var(--mapbg); stroke:var(--mapink); stroke-width:1;
  vector-effect:non-scaling-stroke; }}
.notes {{ margin-top:22px; font-size:13.5px; color:var(--muted); max-width:78ch; }}
.notes b {{ color:var(--ink); font-weight:600; }}
/* Phones.  The map keeps its aspect ratio -- the shader maps the drawing box
   to the viewport, so letterboxing it would stretch the country -- which on a
   narrow screen leaves it short.  What can be given back is the margin around
   it, so the chrome shrinks and the map gets the width. */
@media (max-width:640px) {{
  .wrap {{ padding:16px 12px 36px; }}
  h1 {{ font-size:20px; }}
  p.sub {{ font-size:13px; margin-bottom:12px; }}
  .notes {{ font-size:12.5px; margin-top:16px; }}
  .cap {{ font-size:11.5px; }}
  #hud {{ font-size:11px; padding:3px 7px; left:6px; bottom:6px; }}
  /* The controls keep their full size on a phone: they are the one part of
     the chrome that a finger has to hit. */
  .ctl button {{ font-size:12.5px; }}
  #tip {{ font-size:12px; padding:5px 7px; max-width:70vw;
    white-space:normal; }}
}}
</style>
<div class="wrap">
<h1>{title}</h1>
<p class="sub">{lede} {provenance} Scroll to zoom, drag to pan, hover for a
value.</p>
<div id="stage">
  <canvas id="cv"></canvas>
  <svg class="ov" id="ov" viewBox="0 0 {W} {H}" preserveAspectRatio="none">
    <g id="sc"><g id="mb"></g><g id="bd"></g><g id="lb"></g><g id="tw"></g></g>
  </svg>
  <div id="tip"></div>
  <div id="hud">1.0x</div>
</div>
<!-- The controls sit outside the map rather than on top of it.  Inside, every
     press first reached the pan/zoom surface, which captured the pointer and
     took the click with it; outside, a button is just a button. -->
<div class="ctl">
  <button id="reset" type="button">reset view</button>
  <button id="metros" type="button" role="switch" aria-checked="false"
    ><span class="tr"><span class="kn"></span></span>metro areas</button>
</div>
<div class="legend">{legend}</div>
<p class="notes"><b>What the colour says.</b> {colour}<br><br>
{notes}</p>
</div>
<script>
""" + _GL_JS + """

function resize() {{
  const r=stage.getBoundingClientRect();
  if(!r.width) return;
  const dpr=Math.min(devicePixelRatio||1,2);
  cv.width=Math.round(r.width*dpr); cv.height=Math.round(r.height*dpr);
  draw();
}}
new ResizeObserver(resize).observe(stage);

function draw() {{
  if(!ready||!cv.width) return;
  gl.viewport(0,0,cv.width,cv.height);
  gl.bindFramebuffer(gl.FRAMEBUFFER,null);
  gl.clearColor(0,0,0,0); gl.clear(gl.COLOR_BUFFER_BIT);
  gl.uniform2f(uSize,W,H);
  gl.uniform1f(uK,view.k); gl.uniform2f(uO,view.ox,view.oy);
  gl.uniform1f(uPick,0.0);
  gl.drawElements(gl.TRIANGLES,count,gl.UNSIGNED_INT,0);
  sc.setAttribute('transform',
    `translate(${{view.ox}},${{view.oy}}) scale(${{view.k}})`);
  // Labels hold their size on screen, so both the font and its halo have to
  // be divided by the zoom *and* by the viewBox-to-CSS ratio.  The size they
  // hold shrinks on a narrow screen: 13 px of name over 1,100 px of map is a
  // caption, over 340 px of phone it is a banner.
  const rect=stage.getBoundingClientRect();
  const s=(rect.width ? W/rect.width : 1)/view.k;
  const fit=Math.max(0.72,Math.min(1,rect.width/1000));
  for(const t of document.querySelectorAll('.sl')) {{
    t.style.fontSize=(11*fit*s)+'px'; t.style.strokeWidth=(2.6*fit*s)+'px';
  }}
  const kEff0=view.k*(rect.width>=240 ? rect.width/1100 : 1);
  for(const t of document.querySelectorAll('.sl'))
    t.style.display = kEff0 >= +t.dataset.k ? '' : 'none';
  for(const t of document.querySelectorAll('.tn')) {{
    t.style.fontSize=(12*fit*s)+'px'; t.style.strokeWidth=(3.5*fit*s)+'px';
  }}
  for(const c of document.querySelectorAll('.td'))
    c.setAttribute('r', 2*fit*s);
  // A name appears when there is room for it *on the screen*, not on some
  // notional 1,100 px one, so the test is the zoom scaled by how wide the map
  // actually is.  On a phone that shows the handful that fit and holds the
  // rest back until the reader zooms; on a desktop it is the zoom itself.
  // No screen is narrower than 240 px, so a width below that is a layout that
  // has not settled -- a first paint, a hidden tab, a container still being
  // sized.  Falling back to the plain zoom there matters: scaling by a width
  // of 2 sends the test to zero and hides every label on the map.
  const kEff=view.k*(rect.width>=240 ? rect.width/1100 : 1);
  for(const g of document.querySelectorAll('.tg'))
    g.style.display = kEff >= +g.dataset.k ? '' : 'none';
  hud.textContent=view.k.toFixed(1)+'x';
  pickDirty=true;
}}

// Picking reads one pixel out of an off-screen pass that paints each tile in
// its own index as a colour.  The pass is only redrawn when the view moves.
let pickDirty=true, pickW=0, pickH=0;
function pick(sx,sy) {{
  if(!ready) return 0;
  if(!fb) {{ fb=gl.createFramebuffer(); ftex=gl.createTexture(); }}
  if(pickW!==cv.width||pickH!==cv.height) {{
    pickW=cv.width; pickH=cv.height; pickDirty=true;
    gl.bindTexture(gl.TEXTURE_2D,ftex);
    gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,pickW,pickH,0,gl.RGBA,
                  gl.UNSIGNED_BYTE,null);
    gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.NEAREST);
    gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.NEAREST);
  }}
  gl.bindFramebuffer(gl.FRAMEBUFFER,fb);
  if(pickDirty) {{
    gl.framebufferTexture2D(gl.FRAMEBUFFER,gl.COLOR_ATTACHMENT0,gl.TEXTURE_2D,
                            ftex,0);
    gl.viewport(0,0,pickW,pickH);
    gl.clearColor(0,0,0,0); gl.clear(gl.COLOR_BUFFER_BIT);
    gl.uniform1f(uPick,1.0);
    gl.drawElements(gl.TRIANGLES,count,gl.UNSIGNED_INT,0);
    gl.uniform1f(uPick,0.0);
    pickDirty=false;
  }}
  const px=new Uint8Array(4);
  gl.readPixels(Math.round(sx),Math.round(pickH-sy),1,1,gl.RGBA,
                gl.UNSIGNED_BYTE,px);
  gl.bindFramebuffer(gl.FRAMEBUFFER,null);
  return px[0]|(px[1]<<8)|(px[2]<<16);
}}

function money(x) {{
  if(x>=1e9) return '$'+(x/1e9).toFixed(x<1e10?2:1)+' bn';
  if(x>=1e6) return '$'+(x/1e6).toFixed(x<1e7?1:0)+' m';
  return '$'+Math.round(x/1e3)+'k';
}}

let drag=null;
// Touch: one finger pans, two pinch.  Without this the page could be panned on
// a phone but never zoomed -- the wheel handler below is the only way in, and a
// touchscreen has no wheel.
const pts=new Map();
let pinch=null;
const span=()=>{{
  const [a,b]=[...pts.values()];
  return {{d:Math.hypot(a.x-b.x,a.y-b.y),
          cx:(a.x+b.x)/2, cy:(a.y+b.y)/2}};
}};
function zoomAbout(k,mx,my) {{
  k=Math.min(Math.max(k,1),MAXK);
  const g=k/view.k;
  view.ox=mx-(mx-view.ox)*g; view.oy=my-(my-view.oy)*g;
  view.k=k; clampView(); draw();
}}
stage.addEventListener('pointerdown',e=>{{
  pts.set(e.pointerId,{{x:e.clientX,y:e.clientY}});
  if(pts.size===2) {{
    const s=span(), r=stage.getBoundingClientRect(), u=W/r.width;
    pinch={{d:s.d, k:view.k,
           mx:(s.cx-r.left)*u, my:(s.cy-r.top)*u}};
    drag=null; stage.classList.remove('drag'); tip.style.opacity=0;
    return;
  }}
  drag={{x:e.clientX,y:e.clientY,ox:view.ox,oy:view.oy}};
  stage.classList.add('drag');
  try{{stage.setPointerCapture(e.pointerId);}}catch(_){{}}
}});
stage.addEventListener('pointermove',e=>{{
  const r=stage.getBoundingClientRect();
  if(pts.has(e.pointerId)) pts.set(e.pointerId,{{x:e.clientX,y:e.clientY}});
  if(pinch && pts.size===2) {{
    const s=span();
    if(pinch.d>0) zoomAbout(pinch.k*s.d/pinch.d,pinch.mx,pinch.my);
    return;
  }}
  if(drag && e.buttons!==0) {{
    const s=W/r.width;
    view.ox=drag.ox+(e.clientX-drag.x)*s;
    view.oy=drag.oy+(e.clientY-drag.y)*s;
    tip.style.opacity=0; draw(); return;
  }}
  if(drag) {{ drag=null; stage.classList.remove('drag'); }}
  const dpr=cv.width/r.width;
  const id=pick((e.clientX-r.left)*dpr,(e.clientY-r.top)*dpr);
  if(!id) {{ tip.style.opacity=0; return; }}
  const t=id-1;
  const v=Math.pow(10, TVAL[t]/4096+3);
  if(TGDP) {{
    const g=TGDP[t] ? Math.pow(10, TGDP[t]/4096+3) : 0;
    const yr=g? v/g : 0;
    const dur=yr<1 ? `${{Math.round(yr*365)}} days` : `${{yr.toFixed(1)}} years`;
    const rel=yr/BASE;
    tip.innerHTML=`<b>${{money(v)}}</b> of land<br>`+
      `<b>${{g? money(g) : '&mdash;'}}</b> of output a year<br>`+
      (g ? `<span style="color:var(--muted)">the land is worth <b>${{dur}}</b> of `+
           `that output<br>`+
           (rel>=1 ? `<b>${{rel.toFixed(1)}}&times;</b> the U.S. figure &mdash; dear for the work on it`
                   : `<b>1/${{(1/rel).toFixed(1)}}</b> of the U.S. figure &mdash; cheap for the work on it`)+
           `</span>`
         : `<span style="color:var(--muted)">no workplace here &mdash; the `+
           `output is known only by county, so no ratio is drawn</span>`);
  }} else {{
    tip.innerHTML=`<b>${{money(v)}}</b> {noun}<br>`+
      `<span style="color:var(--muted)">${{money(v/KM2)}} per km&sup2;</span>`;
  }}
  tip.style.opacity=1;
  const tw=tip.offsetWidth, th=tip.offsetHeight;
  tip.style.left=Math.min(Math.max(e.clientX-r.left+14,4),r.width-tw-4)+'px';
  tip.style.top=Math.min(Math.max(e.clientY-r.top-th-12,4),r.height-th-4)+'px';
}});
const lift=e=>{{
  pts.delete(e.pointerId);
  if(pts.size<2) pinch=null;
  drag=null; stage.classList.remove('drag');
}};
stage.addEventListener('pointerup',lift);
stage.addEventListener('pointercancel',lift);
stage.addEventListener('pointerleave',e=>{{lift(e); tip.style.opacity=0;}});
stage.addEventListener('wheel',e=>{{
  e.preventDefault();
  const r=stage.getBoundingClientRect(), s=W/r.width;
  const mx=(e.clientX-r.left)*s, my=(e.clientY-r.top)*s;
  const f=Math.exp(-e.deltaY*0.0015);
  const k=Math.min(Math.max(view.k*f,1),MAXK);
  const g=k/view.k;
  view.ox=mx-(mx-view.ox)*g; view.oy=my-(my-view.oy)*g;
  view.k=k; clampView(); draw();
}},{{passive:false}});
function clampView() {{
  if(!isFinite(view.ox)) view.ox=0;
  if(!isFinite(view.oy)) view.oy=0;
  view.ox=Math.min(0,Math.max(W-W*view.k,view.ox));
  view.oy=Math.min(0,Math.max(H-H*view.k,view.oy));
}}
document.getElementById('reset').onclick=()=>{{
  view={{k:1,ox:0,oy:0}}; draw();
}};
const mbtn=document.getElementById('metros'), mlayer=document.getElementById('mb');
if(!METROS.length) mbtn.style.display='none';
mbtn.addEventListener('click',()=>{{
  const on=mlayer.classList.toggle('on');
  mbtn.setAttribute('aria-checked',on?'true':'false');
}});
</script>
"""


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
